### ISSUE TITLE
Keep A Downloable App In Repo. ♥️

### ISSUE THREAD

**Issue by Rick0987** [LagradOst/CloudStream-2#1]
Loved Your Work And Efforts On This Repo.I Know These Are Present In Release Folder But Just A Quick Suggestion Is That Keep A Downloable App To Test It Out Pretty Quick Without Compiling Your Latest Edits. ♥️

**Comment by BIGEAZY289** [comment]
Apps keep on crashing in my redmi note 4

**Comment by LagradOst** [comment]
> 
> 
> Apps keep on crashing in my redmi note 4

I think this has to do with some key being corrupted, but I am not quite sure yet. I had the same problem even on the latest version, but when I reinstalled it, the problem disappeared. If this keeps happening even after reinstall, open an issue.
