### ISSUE TITLE
[Improvement] Status of the movie/tv show

### ISSUE THREAD

**Issue by santiagoworkana** [LagradOst/CloudStream-2#11]
I don't know how "doable" is this, but it might be worth the try. It would be really cool to have an indicator if the movie will load (if any link will work).
Maybe in the show view, some indicator (green or red) that check in background if any link loads the movie or not. A lot of movies i try have all the links dead. Does it happen to you too?

**Comment by LagradOst** [comment]
Most links are not dead, they just cant be played. You can still download them. Of course I can remove links that give 404, but to do that I have to send a get request to each link generated. For some episodes I get +20 links and I think that it will have an impact on performance if I ping eatch link.

**Comment by santiagoworkana** [comment]
Ohh  ok.. i haven't tried to download them. I'll try!
Is for the movie format?

**Comment by santiagoworkana** [comment]
I just tried to download a movie. Even tough the movie starts to download i had to stop it becasue it made my phone vibrate like every 2/3 secs.  Maybe its a bug?

**Comment by LagradOst** [comment]
yep that is a but, I always run silent mode so I dident know. fixed in 2 sec via builder.SetOnlyAlertOnce(true);

**Comment by santiagoworkana** [comment]
Good! :d
Also i don't know if its possible to play in chromecast from downloaded movies

**Comment by LagradOst** [comment]
" Also i don't know if its possible to play in chromecast from downloaded movies" wdym?

**Comment by santiagoworkana** [comment]
When i click on the movie downloading i can play in the app or external app but no chromecast.

**Comment by LagradOst** [comment]
You are not connected to a device, you cant cast if you are not connected.

**Comment by santiagoworkana** [comment]
great! I connected to the chromecast from a movie detail view and then casted the downlaod! closing the issue :)
