### ISSUE TITLE
Add support for directional remotes (FireStick/GoogleTV)

### ISSUE THREAD

**Issue by daveamato** [LagradOst/CloudStream-2#14]
Please add support for TV remotes.

**Comment by LagradOst** [comment]
will look into that

**Comment by LagradOst** [comment]
I think all dpad binding for Xamarin Forms is auto generated in build time. So there is nothing I can do to add full tv-remote support. I also not have access to test cs-2 with a dpad controller so I cant add it. I would have to make cs-2 to an android native app before that.
