### ISSUE TITLE
Support for apimdb/2embed api

### ISSUE THREAD

**Issue by I-Do-Ketamine** [LagradOst/CloudStream-2#15]
Support for the 2embed/apimdb API.

https://apimdb.net/ or else know as https://www.2embed.ru/ have a nice api that provides some high quality links. 
I thought that support for it would be nice.

**Comment by James-M-Robinson** [comment]
Plus this is the api that https://cineb.net uses.

**Comment by LagradOst** [comment]
https://www.2embed.ru/ is half added, it will only get vidcloud.pro links and will look something like "VidCloud Embed ORG [m3u8]"
