### ISSUE TITLE
you can add more websites please

### ISSUE THREAD

**Issue by alegye** [LagradOst/CloudStream-2#16]
can put these webs kisscartoon kissanime kissasian wwatchseries.com

**Comment by LagradOst** [comment]
full url for all?

**Comment by alegye** [comment]
You can add more pages such as cartoons and anime doramas in
CloudStream-2

**Comment by voltrare** [comment]
[https://wwatchseries.com/](url)
[https//kissasian.sh ](url)
[https://wwatchseries.com
](url)
[https://kisscartoon.sh](url)

**Comment by LagradOst** [comment]
https//kissasian.sh  (cloudflare), https://kisscartoon.sh (antibot), wont be added

**Comment by voltrare** [comment]
Ah i see, thanks for reply

**Comment by LagradOst** [comment]
as for animixplay, it gets links from shiro.io that already has 2 duplicates in this project, dubbedvip and Genoanime so I wont be adding it

**Comment by LagradOst** [comment]
as for https://wwatchseries.com, it looks like it takes links from other sites (most broken or low quality) that is already getting fetched by cs-2 by other sources so I wont add it
