### ISSUE TITLE
Smooth scrolling issue

### ISSUE THREAD

**Issue by GoluLiliput** [LagradOst/CloudStream-2#2]
Hi. The scrolling in the app, for instance in the top 100 movies isn't smooth even on a high end device, maybe it's due to the card growing animation which occurs when the transition of scrolling down occurs in the app. Can we please disable that animation so tht the animation is smoother?

**Comment by LagradOst** [comment]
Can add a setting on that

**Comment by GoluLiliput** [comment]
Please do it brother. It would help a lot😊
