### ISSUE TITLE
Add a option for external downloader

### ISSUE THREAD

**Issue by SanOtaku09** [LagradOst/CloudStream-2#25]
Add 1dm /idm
Support for downloading movies & episode
Many app had already done that
Here the link of the app I'm talking about
[1dm+](https://play.google.com/store/apps/details?id=idm.internet.download.manager.plus) 
[1dm](https://play.google.com/store/apps/details?id=idm.internet.download.manager)

**Comment by LagradOst** [comment]
Copy link > download?

**Comment by SanOtaku09** [comment]
![Screenshot_2021-04-22-21-22-39-463_org telegram messenger](https://user-images.githubusercontent.com/61407097/115745322-f2eb2380-a3b0-11eb-97a2-376337697b13.jpg)

**Comment by LagradOst** [comment]
Is 1dm /idm open source?

**Comment by SanOtaku09** [comment]
He encourages developers to implement 1dm /1dm+

**Comment by LagradOst** [comment]
I wont support another developer if the project is not open source. He can pr this repo, but I wont spend time on stuff that wont improve the open source world myself.

**Comment by SanOtaku09** [comment]
Ok 👍
