### ISSUE TITLE
account sign up

### ISSUE THREAD

**Issue by glorymaster** [LagradOst/CloudStream-2#28]
this app is great and amazing.
suggestions only no need to bother.

1. account sign up - to save progress and bookmarks ( if we accidentally uninstalled the app, we just need to log in and viola our bookmarks well be recovered)
2.  homepage - I hope the word HOME at top center of homepage will be change with app icon ( I think the devs need to change the app Icon, catchy one)
3. category - I hope the categories will put after bookmarks and so on like netflix, we just scroll down. (categories suggestions - popular or trending, horror, crime, sci-fi etc.
4. Last, I  really appreciate if there is a movie, series and anime section.

thank u so much

**Comment by LagradOst** [comment]
1. https://github.com/LagradOst/CloudStreamAccountServer or export data to txt file in settings
2. ????? I am not chaning the icon
3. Cant do because of tecincal reasons 
4. You can select if Top IMDb shows anime or movies in settings, but I doubt that is what you are looking for
