### ISSUE TITLE
Can't play any show or movie

### ISSUE THREAD

**Issue by santiagoworkana** [LagradOst/CloudStream-2#3]
I've downloaded the android version and installed VLC as well.
But for any show or movie i try to play when it goes to VLC its says the link wasn't found or doesn;t work and I can't play anything.
What can it be? Maybe the tokens are failing?

**Comment by santiagoworkana** [comment]
Update: I tried with the experimental player and it works OK with it.
Any plans to add subtitles and chrome support to it?

**Comment by LagradOst** [comment]
1. It is a known issue with some links are failing even if they are "working", this has to do with android cert and it is nothing I can do at the moment. I think xstream generate links that always fails, but can be downloaded, so I just download everything beforehand / download and watching at the same time. I have posted an issue on VLC that some links cant be played even if they can be downloaded. (You can play a link in the browser, that option is coming in the next update)

2. I am currently working on subtitles in the videoplayer, I can parse and download subtitles, but I have not implemented it yet. 

3. chrome support? Do you mean chromecast support? Chromecast was added some time ago, but not in the videoplayer, you have to connect in the episode select screen (next to the name) and then select the chromecast option after generating the links.

**Comment by LagradOst** [comment]
Currently working on an electron app using the core from cloudstream for an desktop app with UI, but I can focus on subtitles for the videoplayer for now.

**Comment by santiagoworkana** [comment]
I saw the chromecast icon and it does connect to the chromecast (i see the blue chromecast icon in the tv) But when i hit play and select chromecast it doesn't play the movie at all. But in the in app player it does play like a charm.

**Comment by LagradOst** [comment]
It should cycle through all the mirrors untill it finds a link it can play. Do anything change on the tv screen when you press the chromecast item in the popup menu?

**Comment by santiagoworkana** [comment]
I connected the chromecast, then tried to play selecting chromecast. Once i select Chomecast the menu closes but nothing else happens neither in the app or in the tv.
The app stays in the show selection/movie screen and the tv keeps showing the blue chromecast icon

**Comment by santiagoworkana** [comment]
Update: I used the android app yesterday and tried a lot to make it workon the chromecast (on the in app player everything goes perfect). I manage to make it work and play on the chromecast, but it seems to be test and fail until it just work.
Some times it just work, but is like 1 out of 10, and not all the time it app shows the controls (30 sec fowards and rewind, pause, stop).
Maybe the chromecast option should show up in the player once a link that works is found? that way the app just cast the working link instead of looking for a workin one?

**Comment by LagradOst** [comment]
I can add a Chromecast start at option, that way you can select a mirror that you think will work/reselect if a mirror dident work.

**Comment by santiagoworkana** [comment]
Thats a great option too! I'm just giving feedback :)
The subtitles will cast as well?

**Comment by LagradOst** [comment]
I added subtitles on chromecast yesterday, it was a pain to implement.

**Comment by santiagoworkana** [comment]
you rock!!

**Comment by LagradOst** [comment]
Subtitles now added in the player, https://cdn.discordapp.com/attachments/551382684560261121/730195705167347742/Screenshot_20200708_005638_com.CloudStreamForms.CloudStreamForms.jpg and this image will show when you are ready to cast https://cdn.discordapp.com/attachments/551382684560261121/730169809408622702/ChromecastLogo6.png

**Comment by LagradOst** [comment]
Will release the update tomorrow or so, will see when it is stable for release.

**Comment by snisnik** [comment]
Wow!! awsome! (its me with my personla account now haha.. i didn't notice i was in my work account haha).
I've cloned the respo but couldn;t make the build to test.. i have some errors but didn't have time to look into them :)

**Comment by LagradOst** [comment]
Published the update now, you can close the issue if you feel like it is solved or tell me if you encounter the same problems. (subtitles on both videoplayer and chromecast should work, but chromecast dosent suport all fonts I think)

**Comment by snisnik** [comment]
Works perfect! 
I'm closing the issue! I'll try to get it up and running so i can contribute to this project. I'll let you know if i have any issue
