### ISSUE TITLE
External Download Managers

### ISSUE THREAD

**Issue by joyful-cambion** [LagradOst/CloudStream-2#36]
Hello,
Can you please add an option to use external download managers like: ADM, 1DM+... 
Because currently the embedded download manager is lacking a lot it's very VANILA, it doesn't have the option of threaded downloads for example, also refresh link option..

**Comment by LagradOst** [comment]
No, I myself will never add support for non open source download managers. Also, all support for cs-2 was dropped a while ago in favor of cs-3
